name: etl
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9
  - pip 
  - numpy
  - pandas
  - bs4
  - ipykernel
  - ipython
  - jupyter
  - matplotlib
  - requests
  - nb_conda_kernels
  - webdriver-manager

